---
all:
  vars:
    ansible_ssh_private_key_file: /home/user1/.ssh/id_rsa
  children:
    test_servers:
      hosts:
        linux-test-1:
          ansible_host: 192.168.0.110
          ansible_user: user
    prod_servers:
      hosts:
        linux-prod-1:
          ansible_host: 192.168.0.112
          ansible_user: vagrant

